import Head from 'next/head'
import { CustomEditor } from '../components/CustomEditor'
// import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={{}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CustomEditor/>
      </main>

      <footer >
       
      </footer>
    </div>
  )
}
